#!/bin/sh



# postinst script for webpy-example
#
# see: dh_installdeb(1)

#_DEB_SYSTEMD_HELPER_DEBUG=1

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# source debconf library
#. /usr/share/debconf/confmodule

# For user-services only, for earch target an extra section! for system-services user deb-systemd*
# put in full unit-name. for example "mkbackup@hourly.service"


case "$1" in

    configure)
        python3 -m pip install --upgrade radicale
        python3 -m pip install --upgrade git+https://github.com/Unrud/RadicaleIMAP
        python3 -m pip install --upgrade git+https://github.com/Unrud/RadicaleInfCloud
        SERVICES="mailserver.target xe-dovecot.service xe-dovecot.socket xe-exim4.service radicale.service"
        for s in $SERVICES; do
            deb-systemd-helper-new unmask $s >/dev/null || true
            if deb-systemd-helper-new --quiet was-enabled $s; then
                    # Enables the unit on first installation, creates new
                    # symlinks on upgrades if the unit file has changed.
                    deb-systemd-helper-new enable $s >/dev/null || true
            else
                    # Update the statefile to add new symlinks (if any), which need to be
                    # cleaned up on purge. Also remove old symlinks.
                    deb-systemd-helper-new update-state $s >/dev/null || true
            fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;

esac

